name = "StructuredOptimization"
uuid = "46cd3e9d-64ff-517d-a929-236bc1a1fc9d"
version = "0.5.0"

[deps]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DSPOperators = "d5a72628-6e2f-430e-82f5-561df0bb8116"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FFTWOperators = "c59a084b-ba08-4f3f-af9e-f4298d6caa94"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProximalAlgorithms = "140ffc9f-1907-541a-a177-7475e0a401e9"
ProximalCore = "dc4f5ac2-75d1-4f31-931e-60435d74994b"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[compat]
AbstractOperators = "0.4"
Combinatorics = "1.0.2"
DSP = "0.5.1 - 0.8"
DSPOperators = "0.1"
DifferentiationInterface = "0.6"
FFTW = "1"
FFTWOperators = "0.1"
LinearAlgebra = "1"
ProximalAlgorithms = "0.8"
ProximalCore = "0.2"
ProximalOperators = "0.17"
RecursiveArrayTools = "1 - 3"
julia = "1.10"
