name = "StructuredOptimization"
uuid = "46cd3e9d-64ff-517d-a929-236bc1a1fc9d"
version = "0.5.0"

[deps]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OperatorCore = "3945cd23-d97e-4db0-9df2-35342dbd287d"
ProximalAlgorithms = "140ffc9f-1907-541a-a177-7475e0a401e9"
ProximalCore = "dc4f5ac2-75d1-4f31-931e-60435d74994b"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[sources]
AbstractOperators = {path = "../AbstractOperators"}
OperatorCore = {path = "../OperatorCore"}
ProximalAlgorithms = {path = "../ProximalAlgorithms.jl"}
ProximalCore = {path = "../ProximalCore.jl"}
ProximalOperators = {path = "../ProximalOperators.jl"}
WaveletOperators = {path = "../AbstractOperators/WaveletOperators"}

[compat]
AbstractOperators = "0.4"
Aqua = "0.8"
Combinatorics = "1.0.2"
DSP = "0.5.1 - 0.8"
DifferentiationInterface = "0.6"
FFTW = "1"
LinearAlgebra = "1"
OperatorCore = "0.1"
ProximalAlgorithms = "0.8"
ProximalCore = "0.2"
ProximalOperators = "0.17"
Random = "1"
RecursiveArrayTools = "1 - 3"
Test = "1"
WaveletOperators = "0.1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WaveletOperators = "f3582904-6f60-4bbd-985d-55eab799bc9d"

[targets]
test = ["Aqua", "LinearAlgebra", "Random", "Test", "WaveletOperators"]
